// Created by iWeb 3.0.4 local-build-20191107

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,85),url:'Videosold_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'Videosold_files/stroke_9.png'},{rect:new IWRect(1,-1,85,2),url:'Videosold_files/stroke_10.png'},{rect:new IWRect(86,-1,2,2),url:'Videosold_files/stroke_11.png'},{rect:new IWRect(86,1,2,85),url:'Videosold_files/stroke_12.png'},{rect:new IWRect(86,86,2,2),url:'Videosold_files/stroke_13.png'},{rect:new IWRect(1,86,85,2),url:'Videosold_files/stroke_14.png'},{rect:new IWRect(-1,86,2,2),url:'Videosold_files/stroke_15.png'}],new IWSize(87,87)),stroke_0:new IWStrokeParts([{rect:new IWRect(-1,1,2,85),url:'Videosold_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'Videosold_files/stroke_1.png'},{rect:new IWRect(1,-1,85,2),url:'Videosold_files/stroke_2.png'},{rect:new IWRect(86,-1,2,2),url:'Videosold_files/stroke_3.png'},{rect:new IWRect(86,1,2,85),url:'Videosold_files/stroke_4.png'},{rect:new IWRect(86,86,2,2),url:'Videosold_files/stroke_5.png'},{rect:new IWRect(1,86,85,2),url:'Videosold_files/stroke_6.png'},{rect:new IWRect(-1,86,2,2),url:'Videosold_files/stroke_7.png'}],new IWSize(87,87))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Videosold_files/VideosoldMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');detectBrowser();Widget.onload();fixAllIEPNGs('Media/transparent.gif');IMpreload('Videosold_files','shapeimage_9','0');IMpreload('Videosold_files','shapeimage_18','0');applyEffects()}
function onPageUnload()
{Widget.onunload();}
